/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerSimulatorRouteImport } from './routes/career-simulator'
import { Route as AiMentorRouteImport } from './routes/ai-mentor'
import { Route as IndexRouteImport } from './routes/index'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerSimulatorRoute = CareerSimulatorRouteImport.update({
  id: '/career-simulator',
  path: '/career-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMentorRoute = AiMentorRouteImport.update({
  id: '/ai-mentor',
  path: '/ai-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-mentor': typeof AiMentorRoute
  '/career-simulator': typeof CareerSimulatorRoute
  '/contact': typeof ContactRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/features': typeof FeaturesRoute
  '/roadmap': typeof RoadmapRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-mentor': typeof AiMentorRoute
  '/career-simulator': typeof CareerSimulatorRoute
  '/contact': typeof ContactRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/features': typeof FeaturesRoute
  '/roadmap': typeof RoadmapRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-mentor': typeof AiMentorRoute
  '/career-simulator': typeof CareerSimulatorRoute
  '/contact': typeof ContactRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/features': typeof FeaturesRoute
  '/roadmap': typeof RoadmapRoute
  '/vision': typeof VisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-mentor'
    | '/career-simulator'
    | '/contact'
    | '/digital-twin'
    | '/features'
    | '/roadmap'
    | '/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-mentor'
    | '/career-simulator'
    | '/contact'
    | '/digital-twin'
    | '/features'
    | '/roadmap'
    | '/vision'
  id:
    | '__root__'
    | '/'
    | '/ai-mentor'
    | '/career-simulator'
    | '/contact'
    | '/digital-twin'
    | '/features'
    | '/roadmap'
    | '/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiMentorRoute: typeof AiMentorRoute
  CareerSimulatorRoute: typeof CareerSimulatorRoute
  ContactRoute: typeof ContactRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  FeaturesRoute: typeof FeaturesRoute
  RoadmapRoute: typeof RoadmapRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-simulator': {
      id: '/career-simulator'
      path: '/career-simulator'
      fullPath: '/career-simulator'
      preLoaderRoute: typeof CareerSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-mentor': {
      id: '/ai-mentor'
      path: '/ai-mentor'
      fullPath: '/ai-mentor'
      preLoaderRoute: typeof AiMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiMentorRoute: AiMentorRoute,
  CareerSimulatorRoute: CareerSimulatorRoute,
  ContactRoute: ContactRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  FeaturesRoute: FeaturesRoute,
  RoadmapRoute: RoadmapRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
